import type { MethodDefinition } from "./types";

export const METHOD_CATALOG: readonly MethodDefinition[] = [
  {
    id: "inner-cinema",
    title: "观电影法",
    subtitle: "一个体验，一个观察",
    family: "distance",
    summary: "把当下剧情放到银幕上，练习看见角色，而不是完全进入角色。",
    durations: [1, 3, 5],
    modes: ["looping", "impulsive", "hurt"],
    outcomes: ["pause", "distance", "choose"],
    evidenceTier: "supported",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: false,
  },
  {
    id: "paced-breath",
    title: "呼吸法",
    subtitle: "数呼气，不追念头",
    family: "settle",
    summary: "跟随每一次呼气数数，把注意力放在数字上，让内在对白慢慢降下来。",
    durations: [1, 3, 5],
    modes: ["tense", "impulsive"],
    outcomes: ["pause", "settle"],
    evidenceTier: "supported",
    eyesOpen: true,
    bodyFocus: true,
    breathChange: true,
    acuteEligible: true,
    premium: false,
  },
  {
    id: "thought-watching",
    title: "觉察法",
    subtitle: "看见小我冒头与消失",
    family: "observe",
    summary: "以旁观者视角看见念头、冲动和执着如何升起、停留、消失。",
    durations: [1, 3, 5, 10],
    modes: ["looping", "curious", "hurt"],
    outcomes: ["distance", "awareness"],
    evidenceTier: "supported",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: false,
  },
  {
    id: "wide-gaze",
    title: "凝视法",
    subtitle: "固定物体，稳定注意",
    family: "settle",
    summary: "凝视一个固定对象，让注意力从内在对白回到稳定、单纯的观看。",
    durations: [1, 3],
    modes: ["tense", "numb", "impulsive"],
    outcomes: ["pause", "settle", "choose"],
    evidenceTier: "experimental",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: true,
    premium: false,
  },
  {
    id: "body-scan",
    title: "内观法",
    subtitle: "观内在，不解释",
    family: "settle",
    summary: "观察身体、能量感或内在变化，只记录感受，不急着解释它。",
    durations: [3, 5, 10],
    modes: ["tense", "numb", "curious"],
    outcomes: ["settle", "awareness"],
    evidenceTier: "supported",
    eyesOpen: false,
    bodyFocus: true,
    breathChange: false,
    acuteEligible: true,
    premium: true,
  },
  {
    id: "person-shift",
    title: "人称替代法",
    subtitle: "把“我”换成名字",
    family: "distance",
    summary: "把“我很生气”替换成“某某正在生气”，让观察距离自然出现。",
    durations: [1, 3],
    modes: ["looping", "hurt"],
    outcomes: ["distance", "choose"],
    evidenceTier: "supported",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: true,
  },
  {
    id: "logout-pause",
    title: "登出法",
    subtitle: "不参与，不解释",
    family: "return",
    summary: "对出现的意识流先不解释、不互动，暂时退出反应界面。",
    durations: [1, 3],
    modes: ["impulsive", "tense", "hurt"],
    outcomes: ["pause", "choose"],
    evidenceTier: "informed",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: true,
    premium: false,
  },
  {
    id: "release",
    title: "宽恕法",
    subtitle: "旁观起伏，保留边界",
    family: "release",
    summary: "不压抑反应，允许情绪释放，同时以旁观者角度看见它的起伏。",
    durations: [5, 10],
    modes: ["hurt", "looping"],
    outcomes: ["release", "distance"],
    evidenceTier: "supported",
    eyesOpen: false,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: true,
  },
  {
    id: "open-awareness",
    title: "合一法",
    subtitle: "记住安静连接的感觉",
    family: "observe",
    summary: "练习回到一种更开放的连接感，把它作为下一次快速安静的锚点。",
    durations: [5, 10],
    modes: ["curious"],
    outcomes: ["awareness", "distance"],
    evidenceTier: "supported",
    eyesOpen: false,
    bodyFocus: true,
    breathChange: false,
    acuteEligible: false,
    premium: true,
  },
  {
    id: "grounded-action",
    title: "意识聚焦法",
    subtitle: "缩小视角，进入细节",
    family: "return",
    summary: "把注意力从大剧情压缩到一个具体对象、感官或细节上，让内在对白降噪。",
    durations: [1, 3],
    modes: ["looping", "tense", "impulsive", "numb", "hurt", "curious"],
    outcomes: ["choose", "pause"],
    evidenceTier: "informed",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: true,
    premium: false,
  },
  {
    id: "trigger-journal",
    title: "稳定法",
    subtitle: "让注意保持静止",
    family: "reflect",
    summary: "观察容易让注意晃动的对象，练习让画面、身体和念头都更稳定。",
    durations: [3, 5, 10],
    modes: ["looping", "hurt", "curious"],
    outcomes: ["distance", "awareness", "choose"],
    evidenceTier: "informed",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: true,
  },
  {
    id: "anchors",
    title: "意识抽离法",
    subtitle: "从近景拉到宏观",
    family: "reflect",
    summary: "把视角从眼前小事拉远到更大的时间线与空间感，暂时离开小我范围。",
    durations: [1, 3],
    modes: ["curious", "looping", "impulsive"],
    outcomes: ["pause", "awareness", "choose"],
    evidenceTier: "informed",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: true,
  },
] as const;

export const METHOD_BY_ID = new Map(METHOD_CATALOG.map((method) => [method.id, method]));
