import type { MethodDefinition } from "./types";

export const METHOD_CATALOG: readonly MethodDefinition[] = [
  {
    id: "inner-cinema",
    title: "内在电影",
    subtitle: "从角色退到观众席",
    family: "distance",
    summary: "把触发拆成三幕，观看反应，而不是进入反应。",
    durations: [1, 3, 5],
    modes: ["looping", "impulsive", "hurt"],
    outcomes: ["pause", "distance", "choose"],
    evidenceTier: "supported",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: false,
  },
  {
    id: "paced-breath",
    title: "轻缓呼吸",
    subtitle: "跟着节奏松开一点",
    family: "settle",
    summary: "不屏息、不用力，用舒适的慢节奏陪身体降速。",
    durations: [1, 3, 5],
    modes: ["tense", "impulsive"],
    outcomes: ["pause", "settle"],
    evidenceTier: "supported",
    eyesOpen: true,
    bodyFocus: true,
    breathChange: true,
    acuteEligible: true,
    premium: false,
  },
  {
    id: "thought-watching",
    title: "看念头",
    subtitle: "把念头当成经过的字幕",
    family: "observe",
    summary: "看见念头升起、停留和落下，不急着证明它。",
    durations: [1, 3, 5, 10],
    modes: ["looping", "curious", "hurt"],
    outcomes: ["distance", "awareness"],
    evidenceTier: "supported",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: false,
  },
  {
    id: "wide-gaze",
    title: "宽视野",
    subtitle: "从隧道注意力回到现场",
    family: "settle",
    summary: "用眼前中性的物体、边缘和距离重新定位当下。",
    durations: [1, 3],
    modes: ["tense", "numb", "impulsive"],
    outcomes: ["pause", "settle", "choose"],
    evidenceTier: "experimental",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: true,
    premium: false,
  },
  {
    id: "body-scan",
    title: "身体扫描",
    subtitle: "感受，不解释",
    family: "settle",
    summary: "从接触点开始，温和注意压力、温度与紧绷。",
    durations: [3, 5, 10],
    modes: ["tense", "numb", "curious"],
    outcomes: ["settle", "awareness"],
    evidenceTier: "supported",
    eyesOpen: false,
    bodyFocus: true,
    breathChange: false,
    acuteEligible: true,
    premium: true,
  },
  {
    id: "person-shift",
    title: "人称切换",
    subtitle: "从“我就是”变成“一个人正在”",
    family: "distance",
    summary: "改写自我指称，把身份判断还原成暂时经验。",
    durations: [1, 3],
    modes: ["looping", "hurt"],
    outcomes: ["distance", "choose"],
    evidenceTier: "supported",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: true,
  },
  {
    id: "logout-pause",
    title: "登出暂停",
    subtitle: "先离开反应界面",
    family: "return",
    summary: "为回复、购买或争辩设置一个明确的返回时间。",
    durations: [1, 3],
    modes: ["impulsive", "tense", "hurt"],
    outcomes: ["pause", "choose"],
    evidenceTier: "informed",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: true,
    premium: false,
  },
  {
    id: "release",
    title: "松开与宽恕",
    subtitle: "放下重播，不放下边界",
    family: "release",
    summary: "可选地松开一部分精神重播，不要求原谅或和解。",
    durations: [5, 10],
    modes: ["hurt", "looping"],
    outcomes: ["release", "distance"],
    evidenceTier: "supported",
    eyesOpen: false,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: true,
  },
  {
    id: "open-awareness",
    title: "开放觉察",
    subtitle: "让声音、感觉和念头共同经过",
    family: "observe",
    summary: "不选一个经验作为自己，练习开放而不追随。",
    durations: [5, 10],
    modes: ["curious"],
    outcomes: ["awareness", "distance"],
    evidenceTier: "supported",
    eyesOpen: false,
    bodyFocus: true,
    breathChange: false,
    acuteEligible: false,
    premium: true,
  },
  {
    id: "grounded-action",
    title: "回到行动",
    subtitle: "只选下一件小事",
    family: "return",
    summary: "把选择写成一个小、具体、可逆的现实动作。",
    durations: [1, 3],
    modes: ["looping", "tense", "impulsive", "numb", "hurt", "curious"],
    outcomes: ["choose", "pause"],
    evidenceTier: "informed",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: true,
    premium: false,
  },
  {
    id: "trigger-journal",
    title: "触发记录",
    subtitle: "看见重复出现的场景",
    family: "reflect",
    summary: "记录场景、方法和结果，不给自己贴类型标签。",
    durations: [3, 5, 10],
    modes: ["looping", "hurt", "curious"],
    outcomes: ["distance", "awareness", "choose"],
    evidenceTier: "informed",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: true,
  },
  {
    id: "anchors",
    title: "觉察锚点",
    subtitle: "让暂停出现在真实生活里",
    family: "reflect",
    summary: "为会议后、打开聊天前或睡前设置安静提示。",
    durations: [1, 3],
    modes: ["curious", "looping", "impulsive"],
    outcomes: ["pause", "awareness", "choose"],
    evidenceTier: "informed",
    eyesOpen: true,
    bodyFocus: false,
    breathChange: false,
    acuteEligible: false,
    premium: true,
  },
] as const;

export const METHOD_BY_ID = new Map(METHOD_CATALOG.map((method) => [method.id, method]));
